### ISSUE TITLE
Library not compatible with Next.js

### ISSUE THREAD

**Issue by H-Root** [andremov/framer-motion-ticker#5]
First of all this library is a life saver

### Desc:
I am use Next 13 Pages Route
Latest version of this library 

the error is as following 
`Hydration failed because the initial UI does not match what was rendered on the server.`

if there is any way to fix this error it would be great B)

**Comment by lin-zaw112** [comment]
I have no problem with nextjs  App router v13.5.3 . Can You  @H-Root  show me your code ?

**Comment by lin-zaw112** [comment]
> First of all this library is a life saver
> ### Desc:
> 
> I am use Next 13 Pages Route Latest version of this library
> 
> the error is as following `Hydration failed because the initial UI does not match what was rendered on the server.`
> 
> if there is any way to fix this error it would be great B)

I have no problem with nextjs  App router v13.5.3 . Can You  @H-Root  show me your code ?

**Comment by H-Root** [comment]
My

> > First of all this library is a life saver
> > ### Desc:
> > I am use Next 13 Pages Route Latest version of this library
> > the error is as following `Hydration failed because the initial UI does not match what was rendered on the server.`
> > if there is any way to fix this error it would be great B)
> 
> I have no problem with nextjs App router v13.5.3 . Can You @H-Root show me your code ?

My code:

```
```

**Comment by H-Root** [comment]
Sorry my fault I clicked close by mistake

My code:

```
import Ticker, { TICKER_DIRECTION_RIGHT } from "framer-motion-ticker";
import React from "react";

const Testimonials = () => {
  const colors = [
    "#632bf3",
    "#f122c8",
    "#f16022",
    "#9ef344",
    "#44d3f3",
  ];

  return (
    <div className="min-h-screen flex items-center justify-center flex-col gap-5 mt-10">
      <Ticker duration={20} direction={TICKER_DIRECTION_RIGHT}>
        {colors.map((item, index) => (
          <div
            key={index}
            style={{
              backgroundColor: item,
              margin: "5px",
              height: "150px",
              width: "200px",
            }}
          />
        ))}
      </Ticker>
    </div>
  );
};

export default Testimonials;
```

which always throws this error ```Hydration failed because the initial UI does not match what was rendered on the server.```.
and I find that this happens only  dev server, but production code doesn't throw any.
@lin-zaw112

**Comment by lin-zaw112** [comment]
> Sorry my fault I clicked close by mistake
> 
> My code:
> 
> ```
> import Ticker, { TICKER_DIRECTION_RIGHT } from "framer-motion-ticker";
> import React from "react";
> 
> const Testimonials = () => {
>   const colors = [
>     "#632bf3",
>     "#f122c8",
>     "#f16022",
>     "#9ef344",
>     "#44d3f3",
>   ];
> 
>   return (
>     <div className="min-h-screen flex items-center justify-center flex-col gap-5 mt-10">
>       <Ticker duration={20} direction={TICKER_DIRECTION_RIGHT}>
>         {colors.map((item, index) => (
>           <div
>             key={index}
>             style={{
>               backgroundColor: item,
>               margin: "5px",
>               height: "150px",
>               width: "200px",
>             }}
>           />
>         ))}
>       </Ticker>
>     </div>
>   );
> };
> 
> export default Testimonials;
> ```
> 
> which always throws this error `Hydration failed because the initial UI does not match what was rendered on the server.`. and I find that this happens only dev server, but production code doesn't throw any. @lin-zaw112

I also tested your code. work just fine on me.
  [https://codesandbox.io/p/github/lin-zaw112/nextjs-motion-ticker/main](url)

**Comment by H-Root** [comment]
It appears that this messages only showed to me during development but production everything is fine thnx everybody and sorry for confusion.
